# Generated by Django 5.0 on 2024-01-24 15:12

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('broker_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('address', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('bedrooms', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('bathrooms', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('parking', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('sqft', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('image_com', models.ImageField(upload_to='images')),
                ('image_1', models.ImageField(blank=True, upload_to='images')),
                ('image_2', models.ImageField(blank=True, upload_to='images')),
                ('is_published', models.BooleanField(default=True)),
                ('post_date', models.DateTimeField(default=datetime.datetime.now)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='broker_app.broker')),
            ],
        ),
    ]
